### ISSUE TITLE
Can this be used for reading configuration files?

### ISSUE THREAD

**Issue by hrj** [wacai/config-annotation#10]
Hi!

When I first saw this project, it seemed that this library could be used for reading configuration files. However, I am not sure I have understood it correctly.

If this is a valid use-case please let me know. I will figure out the example and try to contribute to the documentation.

Thanks!

cc @chidu8

**Comment by zhongl** [comment]
Config-annotation is based on [config](http://github.com/typesafehub/config) as i metioned at top of [README.md](https://github.com/wacai/config-annotation), which is used for reading configuration file.

If you read README carefully, you would find an example project <https://github.com/wacai/config-annotation-example>。

**Comment by hrj** [comment]
Thanks for the response. I am aware of the config library. I am using it in [abandon](https://github.com/hrj/abandon).

My doubt is: how do I read the config file using this macro library? I am in a different context right now, and @chidu8 is helping out with `abandon`, but he is learning scala. A code example would be very helpful to us both. Thx!

(I looked at the example project but didn't find it).
