### ISSUE TITLE
配置项名称不能支持-，也不支持 netty.tcp 的变量类型

### ISSUE THREAD

**Issue by eagoo** [wacai/config-annotation#11]
case ValDef(mods, name, tpt, Block((cd: ClassDef) :: Nil, expr)) =>
      val n = name.toString.replaceAll("\\$u002E","\\.")
      node(level)(s"$n") { //EAOOGQI
        ValDef(mods, name, tpt, Block(generate(cd, s"$owner.$name", level) :: Nil, expr))
      }

    case ValDef(mods, name, tpt, rhs) =>
      try {
        val e = c.eval(c.Expr[Any](Block(q"import scala.concurrent.duration._" :: Nil, rhs)))
        val t = c.typecheck(rhs).tpe
        val n = name.toString.replaceAll("\\$minus","\\-")
        val o = owner.replaceAll("\\$u002E","\\.")
        leaf(level)(s"$n = ${value(t, e)}") //EAGOOQI
        ValDef(mods, name, tpt, get(t, s"$o.$n")) //EAGOOQI
      } catch {
        case e: IllegalStateException => c.abort(vd.pos, e.getMessage)
        case _: Throwable             => vd
      }

通过以上修改可以，使用val `netty.tcp` = news {} 和 val `log-level` = "OFF"

**Comment by eagoo** [comment]
这个项目非常有意思，希望继续发展维护

**Comment by zhongl** [comment]
非常感谢， 若是能给 Pull Request 的就更好了:)

**Comment by zhongl** [comment]
参见 https://github.com/wacai/config-annotation/pull/12
