### ISSUE TITLE
Shouldn't compile while didn't find key

### ISSUE THREAD

**Issue by speedcom** [wacai/config-annotation#13]
Lets say that I want to generate such config:
```
@conf trait resy {
  val host = System.getenv("RESY_HOST")
  val clientId = System.getenv("RESY_CLIENT_ID")
  val secret = System.getenv("RESY_SECRET")
}
```
Let assume also that env RESY_SECRET wasn't set up.
IMHO we should get compilation error while trying to parse it (secret is null).

Currently I'm getting:
```
resy {
  host = "https://resy.com"
  clientId = fakedClientIdXXX
}
```
As wee can see `secret` key is totally ommited.

**Comment by zhongl** [comment]
Config-annotation was not designed for ENV values.

I would be glad with the a PULL REQUEST from you if this problem matters to you.

Thank you for the reporting.
